stages:
  - lint
  - build_docs
  - deploy
  - test

ruff:
  stage: lint
  image: "python:$VERSION"
  parallel:
    matrix:
      - VERSION: ["3.9", "3.13"]
  script:
    - pip install uv
    - make venv
    - uv run ruff check .
    - uv run ruff format .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - tests/**/*
        - prettier_maps_extended/**/*
        - .gitlab/**/*

mypy:
  stage: lint
  image: "python:$VERSION"
  parallel:
    matrix:
      - VERSION: ["3.9", "3.13"]
  script:
    - pip install uv
    - make venv
    - uv run mypy .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - tests/**/*
        - prettier_maps_extended/**/*
        - .gitlab/**/*

test:
  stage: test
  image: qgis/qgis:latest
  script:
    - pip install --break-system-packages -e '.[test]' --no-deps pytest-cov coverage
    - make cov
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - tests/**/*
        - prettier_maps_extended/**/*
        - .gitlab/**/*

build_docs:
  stage: build_docs
  image: python:3.12
  script:
    - pip install uv
    - make venv
    - make docs
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - docs/**/*
